### PR TITLE
made getEnabledSteps accessible from wizardhandler

### PR DESCRIPTION
**Pull request by TheBekker**
Makes it easy to create your own step indicator

### CODE REVIEW

**Comment by jacobscarter** [comment]
@TheBekker Can you fix your white space on the comment and rebase your fork so I can automerge?

Thanks for your contributions!

**Comment by TheBekker** [comment]
Should be up to date now

**Comment by TheBekker** [comment]
Could we get this into master?

**Comment by jacobscarter** [comment]
@TheBekker yeah sorry. I just went through all the issues last night and rounded up about 5 enhancements an a few bug fixes for a 0.6.0 release. Scheduled for January 1st. This and many others will be in master, npm, and bower then. Sorry for the delay. Trying to get back on top of it.

**Comment by jacobscarter** [comment]
added and release 0.6.1

**Pull request closed without merging**
