### PR TITLE
Feature for enabling/disabling wizard steps based on certain conditions

### PR DESCRIPTION
**Pull request by sushil-vishwanathan**
I have done the basic coding for enabling / disabling wizard steps based on dynamic conditions. I have created the unit tests as well to validate that nothing breaks and also to demonstrate usage of this feature.

Please note that I had to add jQuery as a dependency to the karma configuration as jQLite was not enough for some of the DOM operations

Also, I added PhantomJS launcher and Jasmine to the node dependencies as the current configuration perhaps assumes them as globals. You can choose whether or not to accept this bit.

### CODE REVIEW

**Comment by sidahmedbenkhaoua** [comment]
hi evry one i add laste version for make wizard to disabled 
my probleme is i dontkonw what is attribue to add in wz-steps ?

**Comment by jacobscarter** [comment]
@sidahmedbenkhaoua this feature/pull request hasn't been merged yet, I will hopefully get to this very soon and the feature will be available.

**Comment by sidahmedbenkhaoua** [comment]
ok thanks

2015-01-05 16:48 GMT+01:00 Jacob Carter <notifications@github.com>:

> @sidahmedbenkhaoua <https://github.com/sidahmedbenkhaoua> this
> feature/pull request hasn't been merged yet, I will hopefully get to this
> very soon and the feature will be available.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgonto/angular-wizard/pull/72#issuecomment-68726365>.
>



-- 

*BENKHAOUA Sidahmed*
*software developer at iconsoftware <http://www.iconsoftware.dz/>*
Phone:+213 (0) 668 98 10 63
e-mail: *s.benkhaoua@iconsoftware.dz <s.benkhaoua@iconsoftware.dz> *
*Skype:  *sbenkhaoua
*Twitter: **@sBenkhaoua <https://twitter.com/sBenkhaoua>*
︵﻿ ¯\(ツ)/¯ ︵C'est le devoir de chaque homme de rendre au monde au moins
autant qu'il en a reçue︵﻿ ¯\(ツ)/¯ ︵

**Comment by sushil-vishwanathan** [comment]
@jacobscarter I only added the jQuery dependency for the tests to work properly. jQlite seems to be having issues with some of the DOM find methods. It is returning 0 nodes while jQuery is rightly returning the correct number of nodes. Since this is only a test dependency, I thought we could leave it in place

**Comment by myspivey** [comment]
+1 on having this feature. Central to many wizard forms.

**Comment by timmaybrown** [comment]
any progress on getting this merged?

**Comment by jmorvan** [comment]
+1

**Comment by jacobscarter** [comment]
Merged with PR #126 

Thank you @sushil-vishwanathan !

**Comment by sebastialonso** [comment]
I've been using this wizard for a while, so it's good to know that this addition is set to go. Thanks to all involved!!

Could we get an example in the README. The current explanation for wz-disabled is a bit convoluted, isn't it?

**Comment by jacobscarter** [comment]
@sebastialonso README was updated.  Thanks.

**Comment by sebastialonso** [comment]
Awesome. Thanks :)

**Pull request closed without merging**
