### PR TITLE
added description string to step directive, for that special case whe…

### PR DESCRIPTION
**Pull request by TheBekker**
This is for that special case where you want to pass more than just a title, fx for a custom step indicator

### CODE REVIEW

**Comment by jacobscarter** [comment]
@TheBekker Can you fix your white space so I can merge this PR, thanks for your contributions!

**Comment by TheBekker** [comment]
There ya go

**Comment by TheBekker** [comment]
Could we get this into master?

**Comment by jacobscarter** [comment]
These changes are in 0.6.0

**Pull request closed without merging**
