### PR TITLE
Removed lodash dependency

### PR DESCRIPTION
**Pull request by softwaredoug**
Thanks for your awesome directive, we get a ton of usage out of it

We weren't using lodash in our project, and while I wanted your awesome wizard directive, I'm a bit anal about layering on extra dependencies for a couple of reasons:

1. Lodash added size to our JS for a library we don't use. Something like 20-30K after minifying depending on how smart we were with using lodash's official minified build. I think you only use 3-4 functions, some of which have equivelant helpers in angular (isUndefined etc). 
2. Possibility for conflicts with other libraries that use different versions of lodash. A lesser concern, but many prefer finding things to use with a flat dependency graph

So I went ahead and removed lodash in my fork.

- Replaced _ helpers with angular equivelants where possible
- Reimplemented usage of `indexOf` as `stepIdx` function
- Reimplemented usages of `findWhere` with `stepByTitle`

Won't be offended if you think lodash is worth keeping around, my fork can continue to support the crowd that wants to only depend on angular.

Thanks for your consideration
-Doug

### CODE REVIEW

**Comment by eth0izzle** [comment]
:+1:

No need for Lodash/Underscore here.

**Comment by ttbarnes** [comment]
Nice :+1:

**Comment by YidingW** [comment]
:+1:

**Comment by tschneid** [comment]
:+1:

**Comment by ArnauAregall** [comment]
:+1:

**Comment by aarontropy** [comment]
:+1:

**Comment by inferno001** [comment]
:+1:

**Comment by jacobscarter** [comment]
I will pull this down and resolve merge conflicts and include it in the next release.

**Comment by jacobscarter** [comment]
This has been added to the next release, changes were made to the source since this PR so i will close and changes will be seen in 0.6.0

**Pull request closed without merging**
